apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-demo
  namespace: ecr-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecr-demo
  template:
    metadata:
      labels:
        app: ecr-demo
    spec:
      containers:
      - name: ecr-demo
        image: REPLACED_BY_PIPELINE
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ecr-demo-svc
  namespace: ecr-demo
spec:
  selector:
    app: ecr-demo
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
